### ISSUE TITLE
Why no io.Reader and io.Writer interface for snappy?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [golang/snappy#4] opened 2015-05-12 22:48 UTC
```
Interested to find out why there's no streaming interface for snappy?  Wouldn't 
the protocol support it?  Would be nice to know that data streams could use 
snappy too like the json stuff: `json.NewEncoder(w).Encode(obj)` 
```

Original issue reported on code.google.com by `m...@stretchr.com` on 25 Jul 2014 at 5:20

**Comment by nigeltao** [comment] 2015-07-17 07:03
This is a duplicate of #2.

**Closed by nigeltao** 2015-07-17 07:03 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
