### ISSUE TITLE
asm: invalid instruction

### ISSUE THREAD

**Issue by serejja** [golang/snappy#31] opened 2016-04-23 10:45 UTC
Hi,

this is a follow-up to #30. The same build but for golang 1.6 fails for another reason:

```
# github.com/golang/snappy
asm: invalid instruction: 00228 (/home/travis/gopath/src/github.com/golang/snappy/encode_amd64.s:338)	MOVWQZX	table+120(SP)(R11*2), R15
asm: invalid instruction: 00234 (/home/travis/gopath/src/github.com/golang/snappy/encode_amd64.s:343)	MOVW	AX, table+120(SP)(R11*2)
asm: invalid instruction: 00589 (/home/travis/gopath/src/github.com/golang/snappy/encode_amd64.s:506)	MOVW	AX, table+120(SP)(R11*2)
asm: invalid instruction: 00606 (/home/travis/gopath/src/github.com/golang/snappy/encode_amd64.s:515)	MOVWQZX	table+120(SP)(R11*2), R15
asm: invalid instruction: 00610 (/home/travis/gopath/src/github.com/golang/snappy/encode_amd64.s:519)	MOVW	AX, table+120(SP)(R11*2)
asm: asm: assembly of ../../golang/snappy/encode_amd64.s failed
```

Full log is located here, with the error message starting on line 348 - https://gist.github.com/serejja/b0c40abc844ab4ce1c8630afa988e3bb

Just to provide a bit more info (which is in that log anyway):

1. go version go1.4 linux/amd64
2. Ubuntu 12.04.5 LTS, 3.13.0-29-generic
3. gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

Please let me know if this is not related to golang/snappy itself and I should open a ticket on Travis CI.
Thanks!

**Comment by dimchansky** [comment] 2016-04-23 11:25
The same here for commit: https://github.com/golang/snappy/commit/2dbf36527785b61dd460e053f008abafbce9380b

```
# github.com/golang/snappy
asm: invalid instruction: 00235 (G:\Work\My\Go\src\github.com\golang\snappy\encode_amd64.s:338) MOVWQZX table+120(SP)(R11*2), R15
asm: invalid instruction: 00241 (G:\Work\My\Go\src\github.com\golang\snappy\encode_amd64.s:343) MOVW    AX, table+120(SP)(R11*2)
asm: invalid instruction: 00596 (G:\Work\My\Go\src\github.com\golang\snappy\encode_amd64.s:506) MOVW    AX, table+120(SP)(R11*2)
asm: invalid instruction: 00613 (G:\Work\My\Go\src\github.com\golang\snappy\encode_amd64.s:515) MOVWQZX table+120(SP)(R11*2), R15
asm: invalid instruction: 00617 (G:\Work\My\Go\src\github.com\golang\snappy\encode_amd64.s:519) MOVW    AX, table+120(SP)(R11*2)
asm: asm: assembly of github.com\golang\snappy\encode_amd64.s failed
```

go version go1.6.2 windows/amd64

**Comment by peterbourgon** [comment] 2016-04-23 11:37
[Another instance of the failure here](https://drone.io/github.com/go-kit/kit/346).

```
$ go build ./...
# github.com/golang/snappy
asm: invalid instruction: 00228 (/home/ubuntu/src/github.com/golang/snappy/encode_amd64.s:338)	MOVWQZX	table+120(SP)(R11*2), R15
asm: invalid instruction: 00234 (/home/ubuntu/src/github.com/golang/snappy/encode_amd64.s:343)	MOVW	AX, table+120(SP)(R11*2)
asm: invalid instruction: 00589 (/home/ubuntu/src/github.com/golang/snappy/encode_amd64.s:506)	MOVW	AX, table+120(SP)(R11*2)
asm: invalid instruction: 00606 (/home/ubuntu/src/github.com/golang/snappy/encode_amd64.s:515)	MOVWQZX	table+120(SP)(R11*2), R15
asm: invalid instruction: 00610 (/home/ubuntu/src/github.com/golang/snappy/encode_amd64.s:519)	MOVW	AX, table+120(SP)(R11*2)
asm: asm: assembly of ../../golang/snappy/encode_amd64.s failed
```

**Comment by cespare** [comment] 2016-04-23 18:15
Duplicate of #29.

**Comment by microbusinesses** [comment] 2016-04-23 21:49
Same failure here:

https://travis-ci.org/microbusinesses/UserService/builds/125206062

**Comment by nigeltao** [comment] 2016-04-24 00:14
Yeah, duplicate of #29.

**Closed by nigeltao** 2016-04-24 00:14 UTC
